[workspace]
members = [
    "crates/barepdf-core",
    "crates/barepdf-pdf",
    "crates/barepdf-render",
    "crates/barepdf-platform",
    "crates/barepdf-platform-windows",
    "crates/barepdf-i18n",
    "crates/barepdf-ui",
    "crates/barepdf-thumbnail",
    "apps/barepdf",
]
resolver = "2"

[workspace.package]
version = "1.8.0"
edition = "2021"
rust-version = "1.92"
authors = ["BarePDF Contributors"]
license = "MIT"
repository = "https://github.com/Woffluon/BarePDF"

[workspace.dependencies]
crossbeam-channel = "0.5"
lru = "0.18.2"
pdfium-render = { version = "0.9", default-features = false, features = ["pdfium_latest", "thread_safe"] }
raw-window-handle = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slint = { version = "1.9", default-features = false, features = ["std", "backend-winit", "renderer-femtovg", "accessibility", "compat-1-2"] }
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.release-unwind]
inherits = "release"
panic = "unwind"
