[package]
name = "barepdf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "BarePDF: Bare, Fast, Yours. Ultra-lightweight PDF reader executable"

[dependencies]
barepdf-core = { path = "../../crates/barepdf-core" }
barepdf-pdf = { path = "../../crates/barepdf-pdf" }
barepdf-render = { path = "../../crates/barepdf-render" }
barepdf-platform = { path = "../../crates/barepdf-platform" }
barepdf-platform-windows = { path = "../../crates/barepdf-platform-windows" }
barepdf-i18n = { path = "../../crates/barepdf-i18n" }
barepdf-ui = { path = "../../crates/barepdf-ui" }
slint = { version = "1.9", default-features = false, features = ["std", "backend-winit", "renderer-femtovg", "accessibility", "compat-1-2", "raw-window-handle-06"] }
lru.workspace = true
tracing-subscriber = "0.3"
raw-window-handle = "0.6"
ed25519-dalek = { version = "2.2", default-features = false, features = ["std"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
ureq = { version = "3.3", default-features = false, features = ["platform-verifier", "rustls", "win-system-proxy"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

