[package]
name = "barepdf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "BarePDF: Bare, Fast, Yours. Ultra-lightweight PDF reader executable"

[dependencies]
barepdf-core = { path = "../../crates/barepdf-core" }
barepdf-pdf = { path = "../../crates/barepdf-pdf" }
barepdf-render = { path = "../../crates/barepdf-render" }
barepdf-platform = { path = "../../crates/barepdf-platform" }
barepdf-platform-windows = { path = "../../crates/barepdf-platform-windows" }
barepdf-i18n = { path = "../../crates/barepdf-i18n" }
barepdf-ui = { path = "../../crates/barepdf-ui" }
slint = { workspace = true, features = ["raw-window-handle-06"] }
lru.workspace = true
tracing-subscriber.workspace = true
raw-window-handle.workspace = true
ed25519-dalek = { version = "2.2", default-features = false, features = ["std"] }
semver = "1.0"
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
thiserror.workspace = true
tracing.workspace = true
tempfile = "3.27"
ureq = { version = "3.3", default-features = false, features = ["platform-verifier", "rustls", "win-system-proxy"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

