[package]
name = "barepdf-pdf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "PDF Backend traits and PDFium engine adapter for BarePDF"

[dependencies]
barepdf-core = { path = "../barepdf-core" }
pdfium-render.workspace = true

[dev-dependencies]
tempfile = "3"
